### users.getAll
GET http://localhost:8080/users
X-Login: vasya
X-Password: password

### users.getById
GET http://localhost:8080/users/1
X-Login: vasya
X-Password: password

### users.create
POST http://localhost:8080/users
X-Login: vasya
X-Password: password
Content-Type: application/json

{
  "id": 0,
  "login": "tyaru",
  "password": "password",
  "roles": ["ROLE_ADMIN"]
}

### users.update
PUT http://localhost:8080/users
X-Login: vasya
X-Password: password
Content-Type: application/json

{
  "id": 1,
  "login": "vanya111",
  "password": "top-secret!!!!!!!!!!!!!!!!!!!!",
  "roles": ["ROLE_USER", "ROLE_ADMIN"]
}

### users.deleteById
DELETE http://localhost:8080/users/1
X-Login: vasya
X-Password: password




### posts.getAll
GET http://localhost:8080/posts
X-Login: vasya
X-Password: password

### posts.getById
GET http://localhost:8080/posts/1
X-Login: vasya
X-Password: password

### posts.create
POST http://localhost:8080/posts
X-Login: vasya
X-Password: password
Content-Type: application/json

{
  "id": 0,
  "content": "Ва2134ЁЁёз",
  "tags": ["#ромё11ё", "#ВЁИ32НО"],
  "geo": {
    "lat": -65.00,
    "lng": 65.00
  }
}

### posts.update
PUT http://localhost:8080/posts
X-Login: vasya
X-Password: password
Content-Type: application/json

{
  "id": 2,
  "content": "sport",
  "tags": ["#demo", "#fun"],
  "geo": {
    "lat": 65.0,
    "lng": 75.0
  }
}

### posts.deleteById
DELETE http://localhost:8080/posts/5
X-Login: vasya
X-Password: password
